spring.application.name=api-gateway
server.port=8080

management.endpoints.web.exposure.include=health,info

jwt.secret= BXPcTlmqhNCte2gIYNQvaLcPq0UKU8b6MXTN5PSRj4U

# Gateway routes using Eureka service names with load balancing
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=measurement-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://measurement-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/quantities/**

spring.cloud.gateway.server.webflux.routes[2].id=auth-service-oauth2
spring.cloud.gateway.server.webflux.routes[2].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/login/oauth2/**

spring.cloud.gateway.server.webflux.routes[3].id=auth-service-oauth2-init
spring.cloud.gateway.server.webflux.routes[3].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/oauth2/**

spring.cloud.gateway.server.webflux.routes[4].id=auth-service-oauth2-authorization
spring.cloud.gateway.server.webflux.routes[4].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/oauth2/authorization/**

# Optional route (currently commented)
# spring.cloud.gateway.server.webflux.routes[2].id=qma-health
# spring.cloud.gateway.server.webflux.routes[2].uri=lb://measurement-service
# spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/

# Eureka Configuration
eureka.client.serviceUrl.defaultZone=https://eureka-server-lsch.onrender.com/eureka/
eureka.instance.prefer-ip-address=true
