-- ──────────────────────────────────────────────────────────────────────────────
-- Quantity Measurement Application - Database Schema
-- UC16: Production Schema (H2 / MySQL compatible)
-- ──────────────────────────────────────────────────────────────────────────────

-- Main measurements table
CREATE TABLE IF NOT EXISTS QUANTITY_MEASUREMENTS (
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    OPERATION_TYPE VARCHAR(20)  NOT NULL,
    OPERAND1_VALUE VARCHAR(50),
    OPERAND1_UNIT  VARCHAR(50),
    OPERAND2_VALUE VARCHAR(50),
    OPERAND2_UNIT  VARCHAR(50),
    RESULT_VALUE   VARCHAR(50),
    RESULT_UNIT    VARCHAR(50),
    HAS_ERROR      BOOLEAN      NOT NULL DEFAULT FALSE,
    ERROR_MESSAGE  VARCHAR(500),
    CREATED_AT     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index for querying by operation type (COMPARE, CONVERT, ADD, SUBTRACT, DIVIDE)
CREATE INDEX IF NOT EXISTS IDX_QM_OPERATION ON QUANTITY_MEASUREMENTS (OPERATION_TYPE);

-- Index for querying by unit (measurement category lookup)
CREATE INDEX IF NOT EXISTS IDX_QM_UNIT1 ON QUANTITY_MEASUREMENTS (OPERAND1_UNIT);

-- Index for created_at (time-range queries)
CREATE INDEX IF NOT EXISTS IDX_QM_CREATED ON QUANTITY_MEASUREMENTS (CREATED_AT);

-- Audit history table (tracks changes to measurements)
CREATE TABLE IF NOT EXISTS QUANTITY_MEASUREMENT_HISTORY (
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    MEASUREMENT_ID  BIGINT       NOT NULL,
    ACTION          VARCHAR(20)  NOT NULL,   -- INSERT, UPDATE, DELETE
    CHANGED_BY      VARCHAR(100) DEFAULT 'SYSTEM',
    CHANGED_AT      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OLD_VALUE       VARCHAR(500),
    NEW_VALUE       VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS IDX_QMH_MEASUREMENT ON QUANTITY_MEASUREMENT_HISTORY (MEASUREMENT_ID);
CREATE INDEX IF NOT EXISTS IDX_QMH_CHANGED_AT  ON QUANTITY_MEASUREMENT_HISTORY (CHANGED_AT);
