spring.application.name=quantity-measurement-app
server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:mysql://maglev.proxy.rlwy.net:52417/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:DtYEBdbxACTOisHGasFvZyPbDkWVRSBw}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.h2.console.enabled=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

app.jwt.secret=${APP_JWT_SECRET:BXPcTlmqhNCte2gIYNQvaLcPq0UKU8b6MXTN5PSRj4U}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:86400000}
app.oauth2.redirect-uri=${APP_OAUTH2_REDIRECT_URI:http://localhost:4200/oauth2/callback}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:dummy-google-client-id}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:dummy-google-client-secret}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:dummy-github-client-id}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:dummy-github-client-secret}
spring.security.oauth2.client.registration.github.scope=read:user,user:email
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

logging.level.com.app=INFO
logging.level.org.springframework.security=INFO
